stages:
  - build
  - test

build cypress image:
  stage: build
  only: 
    - main
  script:
    - docker build -t cyp .
  
qa testing:
  stage: test
  only:
    - main
  script:
    - docker compose up
  after_script:
    - sudo chown -R gitlab-runner:gitlab-runner ../$CI_PROJECT_NAME
  artifacts:
    reports:
      codequality: index.html
    paths: 
      - /home/gitlab-runner/builds/PQfzMhse/0/sony.tuladhar/designerex/cypress/reports/index.html
    expire_in: 1 week
  dependencies: []

