version: "3"
services:
  # this container will run Cypress test using built-in Electron browser
  e2e-electron:
    image: cyp

      # - ./cypress/reports:/cypress-docker/cypress/reports
    command: [ "--spec", "cypress/e2e/Specific/message.cy.js"]
    volumes:
      - ./cypress:/cypress-docker/cypress

